services:
  app:
    build: .
    volumes:
      - ./:/ASPTest
  db:
    image: mysql:8.0.26
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: ASPTest
    ports:
      - "3306:3306"

volumes:
  db_data: {}
